# Generated by Django 5.0.3 on 2024-03-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
